#spring:
#  application:
#    name: api-gateway
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/product/**
#
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/order/**
#
#        - id: discovery-server-service
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**
#          filters:
#            - RewritePath=/eureka/(?<path>.*), /$\{path}
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#
